#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# openvela AI Contest - collector install script
#
# Install the collector into a contestant demo repo (either generated by
# npx create-vela-workflow or any other track's project). Idempotent, safe to re-run.
#
# Usage:
#   bash install.sh [--team-id contest2026-NNN-form]
#
# Must be executed at the contestant demo repo root.
# TEAM_ID is required (CLI flag takes priority, env var as fallback).

set -eu

usage() {
  cat <<EOF
Usage: $0 [options]

Options:
  --team-id <id>    Team identifier (e.g. team-099-yanxingyu).
                    Falls back to \$TEAM_ID env var.
  -h, --help        Show this help.

This script installs:
  .opencode/plugins/contest-collector.js   (OpenCode plugin)
  .claude/hooks/contest-snapshot.sh        (Claude Code hook)
  .claude/shared/snapshot_core.py          (shared core)
  .claude/contest-settings.snippet.json    (settings snippet for user to merge)
  .gitignore                               (adds logs/.last_push, logs/.cache)

It does NOT install:
  ~/.codex/hooks/                          (user-global, not project-local)
  .kiro/hooks/                             (Kiro adapter not yet implemented)

After running, follow the printed next-steps to:
  1. Merge contest-settings.snippet.json into your .claude/settings.json
  2. Set TEAM_ID env var (or .env)
  3. (Codex users only) Run /hooks → trust inside Codex CLI once
EOF
}

TEAM_ID_OVERRIDE=""
GITHUB_LOGIN_OVERRIDE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --team-id) TEAM_ID_OVERRIDE="$2"; shift 2 ;;
    --github-login) GITHUB_LOGIN_OVERRIDE="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

TEAM_ID_FINAL="${TEAM_ID_OVERRIDE:-${TEAM_ID:-}}"
if [ -z "$TEAM_ID_FINAL" ]; then
  echo "❌ FATAL: TEAM_ID not set. Pass --team-id contest2026-NNN or export TEAM_ID." >&2
  exit 2
fi

if ! echo "$TEAM_ID_FINAL" | grep -qE '^[a-zA-Z][a-zA-Z0-9_-]+$'; then
  echo "❌ FATAL: TEAM_ID '$TEAM_ID_FINAL' must start with a letter and contain only [a-zA-Z0-9_-]" >&2
  exit 2
fi

if [ ! -d .git ]; then
  echo "❌ FATAL: not in a git repository. cd to your demo repo root first." >&2
  exit 2
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

if [ ! -f "$SOURCE_ROOT/adapters/opencode/collector.js" ]; then
  echo "❌ FATAL: cannot locate adapters/. SOURCE_ROOT=$SOURCE_ROOT" >&2
  echo "   Run install.sh from the contest-log-upload/onboarding/ directory." >&2
  exit 2
fi

if [ -n "$GITHUB_LOGIN_OVERRIDE" ]; then
  GITHUB_LOGIN_FINAL="$GITHUB_LOGIN_OVERRIDE"
  GITHUB_LOGIN_SOURCE="cli-arg"
else
  DETECT_OUT=$(GITHUB_LOGIN="${GITHUB_LOGIN:-}" python3 "$SOURCE_ROOT/adapters/shared/get_github_login.py" "$REPO_ROOT" 2>&1) || DETECT_OUT=""
  GITHUB_LOGIN_FINAL=$(echo "$DETECT_OUT" | awk -F'\t' '{print $1}')
  GITHUB_LOGIN_SOURCE=$(echo "$DETECT_OUT" | awk -F'\t' '{print $2}')
fi

if [ -z "$GITHUB_LOGIN_FINAL" ] || ! echo "$GITHUB_LOGIN_FINAL" | grep -qE '^[A-Za-z0-9][A-Za-z0-9-]{0,38}$'; then
  echo "❌ FATAL: cannot determine GitHub username." >&2
  echo "   Try one of:" >&2
  echo "     1. gh auth login" >&2
  echo "     2. bash install.sh --github-login your-github-name --team-id $TEAM_ID_FINAL" >&2
  echo "     3. export GITHUB_LOGIN=your-github-name && bash install.sh --team-id $TEAM_ID_FINAL" >&2
  exit 2
fi

echo "📦 Installing contest collector to: $REPO_ROOT"
echo "   TEAM_ID:      $TEAM_ID_FINAL"
echo "   GITHUB_LOGIN: $GITHUB_LOGIN_FINAL  (source: $GITHUB_LOGIN_SOURCE)"
echo ""

mkdir -p .opencode/plugins
cp "$SOURCE_ROOT/adapters/opencode/collector.js" .opencode/plugins/contest-collector.js
echo "✅ .opencode/plugins/contest-collector.js"

mkdir -p .claude/shared .claude/commands
cp "$SOURCE_ROOT/adapters/shared/snapshot_core.py" .claude/shared/snapshot_core.py
cp "$SOURCE_ROOT/adapters/shared/get_github_login.py" .claude/shared/get_github_login.py
cp "$SOURCE_ROOT/commands/contest-snapshot.md" .claude/commands/contest-snapshot.md
echo "✅ .claude/commands/contest-snapshot.md (slash command: /contest-snapshot)"

echo "✅ .claude/shared/snapshot_core.py + .claude/shared/get_github_login.py (used by export-session.py and the slash command)"

mkdir -p tools
cp "$SOURCE_ROOT/tools/render-log.py" tools/render-log.py
cp "$SOURCE_ROOT/tools/validate-log.py" tools/validate-log.py
cp "$SOURCE_ROOT/tools/export-session.py" tools/export-session.py
chmod +x tools/render-log.py tools/validate-log.py tools/export-session.py
echo "✅ tools/render-log.py + tools/validate-log.py + tools/export-session.py"

mkdir -p schema
cp "$SOURCE_ROOT/schema/event.schema.json" schema/event.schema.json
cp "$SOURCE_ROOT/schema/manifest.schema.json" schema/manifest.schema.json
echo "✅ schema/event.schema.json + schema/manifest.schema.json (required by validate-log.py)"

cp "$SOURCE_ROOT/onboarding/JUDGE_GUIDE.md" JUDGE_GUIDE.md
echo "✅ JUDGE_GUIDE.md (judge guide, at contestant repo root)"

cp "$SOURCE_ROOT/onboarding/USAGE.md" USAGE.md
echo "✅ USAGE.md (contestant usage guide, at contestant repo root)"

GITIGNORE_ENTRIES=("logs/**/.cache/" "logs/**/*.tmp")
[ -f .gitignore ] || touch .gitignore
for entry in "${GITIGNORE_ENTRIES[@]}"; do
  if ! grep -qxF "$entry" .gitignore; then
    echo "$entry" >> .gitignore
  fi
done
echo "✅ .gitignore updated"

if [ -f .env ] && grep -qE '^TEAM_ID=' .env; then
  echo "✓  .env already has TEAM_ID; identity is now stored in ~/.claude/contest-collector.env"
fi

USER_CLAUDE_DIR="${HOME}/.claude"
USER_CONTEST_DIR="$USER_CLAUDE_DIR/contest-shared"
USER_STAGING_DIR="$USER_CLAUDE_DIR/contest-collector-staging"
USER_GLOBAL_ENV="$USER_CLAUDE_DIR/contest-collector.env"
mkdir -p "$USER_CLAUDE_DIR" "$USER_CONTEST_DIR" "$USER_STAGING_DIR"

if [ ! -f "$USER_GLOBAL_ENV" ]; then
  cat > "$USER_GLOBAL_ENV" <<EOF
TEAM_ID=$TEAM_ID_FINAL
GITHUB_LOGIN=$GITHUB_LOGIN_FINAL
EOF
  echo "✅ ~/.claude/contest-collector.env (your contest identity, machine-wide)"
else
  echo "✓  ~/.claude/contest-collector.env already exists, leaving it alone"
fi

cp "$SOURCE_ROOT/adapters/shared/snapshot_core.py" "$USER_CONTEST_DIR/snapshot_core.py"
cp "$SOURCE_ROOT/adapters/shared/get_github_login.py" "$USER_CONTEST_DIR/get_github_login.py"

cat > "$USER_CONTEST_DIR/contest-snapshot.sh" <<'GLOBAL_HOOK_EOF'
#!/usr/bin/env bash
set -eu

GLOBAL_ENV="$HOME/.claude/contest-collector.env"
[ -f "$GLOBAL_ENV" ] || exit 0

set -a
. "$GLOBAL_ENV"
set +a

[ -z "${TEAM_ID:-}" ] && exit 0

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec python3 "$SCRIPT_DIR/snapshot_core.py" --tool claude-code
GLOBAL_HOOK_EOF
chmod +x "$USER_CONTEST_DIR/contest-snapshot.sh"
echo "✅ ~/.claude/contest-shared/ (global hook for cwd-outside-repo scenarios)"

USER_SETTINGS="$USER_CLAUDE_DIR/settings.json"
GLOBAL_HOOK_CMD="bash $USER_CONTEST_DIR/contest-snapshot.sh"

python3 - "$USER_SETTINGS" "$GLOBAL_HOOK_CMD" <<'MERGE_PY'
import json, sys, os
path, cmd = sys.argv[1], sys.argv[2]
data = {}
if os.path.exists(path):
    with open(path) as f:
        try:
            data = json.load(f)
        except Exception:
            print(f"⚠️  {path} exists but is not valid JSON; backing up and re-creating")
            os.rename(path, path + ".contest-backup")
            data = {}
hooks = data.setdefault("hooks", {})
contest_marker = "contest-shared/contest-snapshot.sh"
for event in ("Stop", "SessionEnd"):
    arr = hooks.setdefault(event, [])
    if any(contest_marker in str(h) for group in arr for h in group.get("hooks", [])):
        continue
    arr.append({"hooks": [{"type": "command", "command": cmd, "timeout": 30}]})
with open(path, "w") as f:
    json.dump(data, f, indent=2)
print(f"✅ {path} updated (Stop+SessionEnd registered)")
MERGE_PY

echo ""
echo "─────────────────────────────────────────────────────"
echo "📋 NEXT STEPS"
echo "─────────────────────────────────────────────────────"
echo ""
echo "1. (one-time) Verify the install:"
echo "   bash $SOURCE_ROOT/onboarding/verify-setup.sh"
echo ""
echo "2. Start working with AI."
echo "   Every session is staged silently to:"
echo "     ~/.claude/contest-collector-staging/$GITHUB_LOGIN_FINAL/"
echo "   This stays on your machine. NOTHING reaches the demo repo automatically."
echo ""
echo "3. When you finish a session you want to submit, ask the AI:"
echo "     'archive this session into the contest repo'  (or any equivalent phrasing)"
echo "   or run the slash command:"
echo "     /contest-snapshot"
echo "   or run the script directly:"
echo "     python3 tools/export-session.py --latest"
echo ""
echo "4. Commit + push logs as part of your normal flow:"
echo "     git add logs/ && git commit -s -m 'logs: capture session' && git push"
echo ""
